### ISSUE TITLE
Wiki still refers to IReason and IExceptionReason after type rename

### ISSUE THREAD

**Issue by VilleSalonen** [bfren/maybe#107]
For example here: https://github.com/bfren/maybe/wiki/Some-and-None

Types were renamed here: https://github.com/bfren/maybe/commit/1c2adf4eab4c5a204c9ae8ba6e1c7c1ac6faa141

**Comment by bfren** [comment]
You're absolutely right, thanks for pointing it out - and reminding me I need to do some more work on the wiki!

**Comment by bfren** [comment]
All done!
